### ISSUE TITLE
Unable to run sage sample experiment.

### ISSUE THREAD

**Issue by agottipati9** [Soheil-ab/sage#1]
Hi when I try to run the sample script, I get the following error with no output data. Can you provide some guidance on how to resolve the issue? Thanks.

![image](https://github.com/Soheil-ab/sage/assets/44129794/9dc589d0-20ae-408b-adf1-ec108c34bbf3)

**Comment by Soheil-ab** [comment]
Hi, you need to run the script with a **normal user** and **not as the root**.
