### ISSUE TITLE
I can't install the nvidia driver in 4.19.112-0062 kernel. like the issue "I am now relatively certain that the issue is related to the code '#include <sys/socket.h>' line28 in the '/usr/src/linux-headers-4.19.112-0062/include/linux/if.h' file, which references a user-space library. This issue seems similar to the one described in this GitHub issue: https://github.com/openzfs/zfs/issues/10601."

### ISSUE THREAD

**Issue by yhcchaos** [Soheil-ab/sage#10]
I am now relatively certain that the issue is related to the code '#include <sys/socket.h>' line28 in the '/usr/src/linux-headers-4.19.112-0062/include/linux/if.h' file, which references a user-space library. This issue seems similar to the one described in this GitHub issue: https://github.com/openzfs/zfs/issues/10601.

In fact, there may be other problems with the kernel module that are preventing the installation of network card drivers and NVIDIA GPU drivers (basically, anything that relies on kernel header files). I would like to know if you can confirm this issue. When using Sage for inference, did you use only the CPU, or were there any GPU-related dependencies?

_Originally posted by @intothesea in https://github.com/Soheil-ab/sage/issues/5#issuecomment-1783802412_

**Comment by yhcchaos** [comment]
Here is the install log.
[Uploading nvidia-installer.log…]()

**Comment by Soheil-ab** [comment]
Discussed before here: https://github.com/Soheil-ab/sage/issues/5#issuecomment-1793475722
