### ISSUE TITLE
Sage mininet usage 

### ISSUE THREAD

**Issue by Aruuni** [Soheil-ab/sage#11]
Can the sage code be adapted to tested using mininet? And if so how would one go about doing that?

**Comment by Soheil-ab** [comment]
Mininet's webpage (https://mininet.org) mentions that "Mininet creates a realistic virtual network, running **real kernel**, switch and **application code**, on a single machine (VM, cloud or native)".  So, I assume that means you should be able to run Sage too.! Mininet is just a network emulator, after bringing up a network, you can run any application code (e.g., Sage's code) on top of a working kernel (e.g., Sage's patched kernel). You just need to make sure that you're following the right syntax to call the applications on the server and client sides. 

Please check out Mininet's tutorials for that (e.g., search for "Run a simple web server and client" in 
[here](https://mininet.org/walkthrough/)) ...
