### ISSUE TITLE
Unable to run sample tests.

### ISSUE THREAD

**Issue by agottipati9** [Soheil-ab/sage#2]
Hi thank you for the speedy response. Executing the script without root still leads to no data output. 
![image](https://github.com/Soheil-ab/sage/assets/44129794/05439fc4-e280-48fe-90f1-dab14772f297)
My error seems to stem from the last line of server.sh. What is the last line supposed to execute? I ran through the setup again to make sure I had the environment configured properly but am still seeing the error. Thanks.

**Comment by Soheil-ab** [comment]
Hi, you need to first compile/build Sage before you can run it (README is updated!). The error ".../sage no such file or directory" tells that the binary doesn't exist.

You can do this:

cd ~/sage/sage_rl
bash build.sh
