### ISSUE TITLE
Question about linux-patch

### ISSUE THREAD

**Issue by SwaggyZhang** [Soheil-ab/sage#4]
With Ubuntu16.04 (Kernel 4.15.0.142), dpkg the .deb and the kernel patch was installed.

But when loading the modified kernel 4.19, the process is stuck in ' load inital ramdisk...' and cannot boot up.

Could you give me some advice and help me to deal with it?

**Comment by Soheil-ab** [comment]
Can you give more info abt your setting?

**Comment by SwaggyZhang** [comment]
> Can you give more info abt your setting?

My device is a lenovo Yoga Slim 7i Pro X laptop with i9-12900H, 32GB RAM and RTX 3050 dGPU.

To study your code, I prepared a brand new Ubuntu 16.04 but did not erase the win11. 

But I cannot load the kernel in your repo.

Besides, I found that there was an extra kernel (4.15.112, **not the initial one of Ubuntu 16.04**) in the grub list after installing the modified kernel 4.19.

Thank you for your reply!

**Comment by intothesea** [comment]
> > Can you give more info abt your setting?
> 
> My device is a lenovo Yoga Slim 7i Pro X laptop with i9-12900H, 32GB RAM and RTX 3050 dGPU.
> 
> To study your code, I prepared a brand new Ubuntu 16.04 but did not erase the win11.
> 
> But I cannot load the kernel in your repo.
> 
> Besides, I found that there was an extra kernel (4.15.112, **not the initial one of Ubuntu 16.04**) in the grub list after installing the modified kernel 4.19.
> 
> Thank you for your reply!

I had the same problem before. Following some tutorials I updated the **bios** of my motherboard to the latest version, after which it started up normally

**Comment by SwaggyZhang** [comment]
> > > Can you give more info abt your setting?
> > 
> > 
> > My device is a lenovo Yoga Slim 7i Pro X laptop with i9-12900H, 32GB RAM and RTX 3050 dGPU.
> > To study your code, I prepared a brand new Ubuntu 16.04 but did not erase the win11.
> > But I cannot load the kernel in your repo.
> > Besides, I found that there was an extra kernel (4.15.112, **not the initial one of Ubuntu 16.04**) in the grub list after installing the modified kernel 4.19.
> > Thank you for your reply!
> 
> I had the same problem before. Following some tutorials I updated the **bios** of my motherboard to the latest version, after which it started up normally

Thank you for your help!
I will have a try!

**Comment by intothesea** [comment]
> > > > Can you give more info abt your setting?
> > > 
> > > 
> > > My device is a lenovo Yoga Slim 7i Pro X laptop with i9-12900H, 32GB RAM and RTX 3050 dGPU.
> > > To study your code, I prepared a brand new Ubuntu 16.04 but did not erase the win11.
> > > But I cannot load the kernel in your repo.
> > > Besides, I found that there was an extra kernel (4.15.112, **not the initial one of Ubuntu 16.04**) in the grub list after installing the modified kernel 4.19.
> > > Thank you for your reply!
> > 
> > 
> > I had the same problem before. Following some tutorials I updated the **bios** of my motherboard to the latest version, after which it started up normally
> 
> Thank you for your help! I will have a try!

If it is successful, please try to see if the NIC driver and GPU driver can be installed correctly, I am having problems with this
