### ISSUE TITLE
Questions about the linux patch

### ISSUE THREAD

**Issue by intothesea** [Soheil-ab/sage#5]
I have installed the 4.19 kernel version as instructed on a **physical machine**. And I need to reinstall the NIC driver. However, I get an error about missing _/lib/modules/linux-4.19-xx/build_ . 

Therefore, I would like to ask you whether you installed the linux patch on a virtual machine or a physical machine and whether you have encountered problems that require reinstalling drivers such as the NIC driver.

**Comment by intothesea** [comment]
I would also like to know if there are any other effects on the physical machine as a result of changing a custom kernel version

**Comment by Soheil-ab** [comment]
Hi @intothesea,
Some notes regarding your questions.

1) In our setting, we had multiple servers dedicated to different tasks, some using our own patched kernel, some using vanilla versions. For example, the whole training process was conducted on servers with vanilla kernels. If you read the SIGCOMM'23 paper, you'll realize that it was part of our key motivations to be able to simply use the existing general-purpose ML clusters (without any change) for the training part.

2) We didn't use any VMs in our setting. 

3) For the patched servers, tbh I don't remember any issues with NIC drivers. When generating the Debian kernel files, I tried to enable different general drivers by default. That said, if time permits (which unfortunately is not the case in a near future for me), I'll try to clean-up the source code of the patched kernel and enable interested users to build their own patches (and enable/disable diff drivers). 

4) re the effects on the physical machine: no, there wouldn't be any impact on "physical" machine.

Hope these help.

**Comment by intothesea** [comment]
> Hi @intothesea, Some notes regarding your questions.
> 
> 1. In our setting, we had multiple servers dedicated to different tasks, some using our own patched kernel, some using vanilla versions. For example, the whole training process was conducted on servers with vanilla kernels. If you read the SIGCOMM'23 paper, you'll realize that it was part of our key motivations to be able to simply use the existing general-purpose ML clusters (without any change) for the training part.
> 2. We didn't use any VMs in our setting.
> 3. For the patched servers, tbh I don't remember any issues with NIC drivers. When generating the Debian kernel files, I tried to enable different general drivers by default. That said, if time permits (which unfortunately is not the case in a near future for me), I'll try to clean-up the source code of the patched kernel and enable interested users to build their own patches (and enable/disable diff drivers).
> 4. re the effects on the physical machine: no, there wouldn't be any impact on "physical" machine.
> 
> Hope these help.

First of all, thank you very much for your response. I will continue to work on resolving the issues with the patched Linux kernel. I installed Ubuntu 16.04 alongside Windows 11, and I suspect that the problems I'm experiencing might be related to a faulty kernel installation, causing issues with network cards, graphics drivers, and other components.

Secondly, I would like to confirm the role of this kernel. Is it the TCP kernel module mentioned in the paper 'Computers Can Learn from the Heuristic Designs and Master Internet Congestion Control'? It is used for user-space and kernel-space interaction, providing observation values and executing actions based on model outputs (such as the 'getsock( sock_for_cnt[i], SOL_TCP, TCP_INFO, (void *)&sage_info, &sage_info_length)' and 'setsockopt(sock_for_cnt[i], IPPROTO_TCP,TCP_CWND, &target_ratio, sizeof(target_ratio))' codes for TCP congestion control).

**Comment by intothesea** [comment]
I am now relatively certain that the issue is related to the code '#include <sys/socket.h>' line28 in the '/usr/src/linux-headers-4.19.112-0062/include/linux/if.h' file, which references a user-space library. This issue seems similar to the one described in this GitHub issue: https://github.com/openzfs/zfs/issues/10601.

In fact, there may be other problems with the kernel module that are preventing the installation of network card drivers and NVIDIA GPU drivers (basically, anything that relies on kernel header files). I would like to know if you can confirm this issue. When using Sage for inference, did you use only the CPU, or were there any GPU-related dependencies?

**Comment by Soheil-ab** [comment]
Hi, the main point of having a patched kernel is to enable TCP PURE that you need to run Sage during the inference.

re the inference, for the SIGCOMM'23 paper, we only used CPU. 

Hope that helps

**Comment by Han19970605** [comment]
I have encountered the same question. I cannot install NVIDIA drivers with this version of kernel, It seems I can only use CPU to run sage..

**Comment by intothesea** [comment]
> I have encountered the same question. I cannot install NVIDIA drivers with this version of kernel, It seems I can only use CPU to run sage..

Train the model using GPU and then test it with CPU ⁺◟(*'꒳'*)
