### ISSUE TITLE
Question on running sample test

### ISSUE THREAD

**Issue by Rumjxl** [Soheil-ab/sage#6]
After the installation, something wrong happens when running run_sample.sh. ERROR seems to be:   [Cntthread] null alpha.

Could you give me some advice of debugging? 
![Uploading Screenshot from 2023-11-01 20-17-58.png…]()

**Comment by Rumjxl** [comment]
![Screenshot from 2023-11-01 20-17-58](https://github.com/Soheil-ab/sage/assets/49086585/145f6d77-b105-4a6d-82df-a6a399088c6e)

**Comment by Soheil-ab** [comment]
Hi,

Alpha is the output of the python code (this is the action decided by the RL part), so you may check if the python code is running smoothly. **Generally**, this should not happen but you can ignore it if this only happens occasionally.
