### ISSUE TITLE
Question about training and policy collection

### ISSUE THREAD

**Issue by July-jun** [Soheil-ab/sage#7]
I have two problems and hope you can give me some advise. 

1. Regarding policy collection, generating a simple dataset with parts of CCs (cubic and reno) is okay. However, I encounter a 'connection failed' error when trying to collect data for other CCs (e.g., vegas, bbr).
![image](https://github.com/Soheil-ab/sage/assets/149641955/13e9b75d-5720-4da2-89da-7af3ca789949)

2. As for training, after obtaining the final dataset, I face the issue of memory consumption continuously increasing until the process is killed."
![image](https://github.com/Soheil-ab/sage/assets/149641955/6124cdf1-53be-4ee1-87aa-9b22c62fd62a)

**Comment by Soheil-ab** [comment]
Hi,

re the first issue, make sure that you have enabled "other" CC schemes in Kernel before running the scripts for them. E.g., check out "sysctl net.ipv4.tcp_congestion_control" and how to use this command ...

re the 2nd issue, this tells me that the GPU that you're using doesn't have enough memory for that shuffle buffer, so simply reduce the size of shuffle buffer to have it fit to your setting. That will impact the results of your training though.
