### ISSUE TITLE
Any plan to release the collected dataset?

### ISSUE THREAD

**Issue by mrbeann** [Soheil-ab/sage#8]
Dear Dr. Abbasloo. Firstly, thank you for this really fantastic work. I was wondering if you have any plan to release the collected pool of policies with 60 million data points. It will greatly advance this research field. Thanks!

**Comment by Soheil-ab** [comment]
Hi @mrbeann, thx for ur kind words.
We've already released the tools to generate the dataset [here](https://github.com/Soheil-ab/ccBench/tree/main/pantheon-modified/third_party/tcpdatagen). That said, currently there is no plan to release the dataset itself.
