### ISSUE TITLE
sage's kernel code

### ISSUE THREAD

**Issue by yhcchaos** [Soheil-ab/sage#9]
Hi, Thanks for your excellent work of sage cc algorithm. I'm recently designing my new cc algorithm，but I don’t have a deep understanding of the linux kernel. So i have some problems in Integrating my congestion control algorithms into the kernel. Could you please  tell me where to find the the sage's linux kernel code(like the cubic's source code net/ipv4/tcp_cubic.c)?  

I found that you use the setsockopt to acquire the network stats(TCP_INFO sock option) as the rl model's  input and also use the setsockopt to change the cc window(TCP_CWND sock option), could you please tell me where to find the source code?

Please forgive me for bothering you with such basic programming questions. Thanks very much if you can help me.

**Comment by Soheil-ab** [comment]
Hi,
The Kernel source code is not included with sage rep. However, regarding your questions, I suggeat that you take a look at the Orca's Linux Patch (including the source code, here: https://github.com/Soheil-ab/Orca/blob/master/linux/linux-4-13-1-orca-0521%2Bc2tcp.patch). This will help you to go over a few examples of patched CC designs such as C2TCP, DeepCC, & Orca.

**Comment by han0602** [comment]
Hi @Soheil-ab , the https://github.com/Soheil-ab/Orca/blob/master/linux/linux-4-13-1-orca-0521%2Bc2tcp.patch only shows part of the kernel code.
For example, how can I get the full code of 'linux-4.13.1-pure-bbr/net/ipv4/tcp_cubic.c'? I tried to use the command 'dpkg -x package_name.deb' to extract the contents of the Linux kernel .deb file, but it could not show the customised file, like tcp_cubic.c

Could you please share the kernel source code? That will be very helpful in modifying some CC logic in the Kernel.

Thanks.
